library(datasets)
hist(airquality$Ozone, main = "Airquality WRT Ozone")
with(airquality, plot(Wind, Ozone))
#Annotation point and colors.
with(airquality, plot(Wind,Ozone, pch= 25))
with(airquality, plot(Wind,Ozone, pch = 23, col= 'Blue'))
airquality<- transform(airquality, Months=factor(Month))
boxplot(Ozone ~ Month, airquality, xlab = "Month", ylab = "Ozone(ppl)")
with(airquality,plot(Wind, Ozone, main="Ozone And windd in New York"))
with(subset(airquality, Month==5),points(Wind, Ozone, col ="blue"))
with(subset(airquality, Month!=5), points(Wind, Ozone, col ="red"))
legend("topright",pch=1,col = c("blue","red"),legend=c("May", "Other Months"))
model<- lm(Ozone ~ Wind, airquality)
abline(model,lwd=2 )
