library(ggplot2)
data(mpg)
qplot(displ, hwy, data = mpg, geom = c("point", "smooth"))
qplot(hwy, data = mpg, fill= drv)
qplot(displ, hwy, data = mpg, facets = . ~ drv )
qplot(displ, hwy, data = mpg, facets = . ~ drv )
qplot(displ, hwy, data = mpg, facets =drv ~ fl )
qplot(hwy, data = mpg, facets =drv ~ fl , binwidth= 2 )
qplot(log(eno), data= maacs)
qplot(log(eno), data = maacs, fill= mopos)
qplot(log(eno), data= maacs, geom = "density")
qplot(log(eno), data = maacs, geom = "density", color= mopos)
qplot(log(pm25), log(eno), data= maacs)
qplot(log(pm25), log(eno), data = maacs, shape= mopos)
qplot(log(pm25), log(eno), data = maacs, color= mopos)
qplot(log(pm25), log(eno), data = maacs, color= mopos, geom = c("point","smooth"), method= "lm")
qplot(log(pm25), log(eno), data = maacs, geom = c("point","smooth"), method="lm", facets = . ~ mopos)
maacs2<- read.csv("bmi_pm25_no2_sim-210103-151358.csv", header = TRUE)
head(maacs2)
g<- ggplot(maacs2, aes(logpm25, NocturnalSympt))
summary(g)
plt<- g + geom_point()
print(plt)
g+geom_point()+ geom_smooth(method = "lm") + facet_grid(. ~ bmicat)
g+ geom_point(color = "steelblue", size = 4, alpha = 1/2)
g+ geom_point(aes( color = bmicat))+ labs(title = "MAACS2") + labs(x = expression("log" * PM[2.5]),
                                                                  y = "NocturnalSympt")
              
g+ geom_point(aes(color = bmicat), size = 4, alpha = 1/2) +
geom_smooth(size = 1, linetype= 5, method = "lm", se = FALSE)+ theme_bw(base_family = "Times" )
testdat<- data.frame(x=1:100 , y = rnorm(100))
testdat[50,2]<- 100
g<- ggplot(testdat, aes(x =x , y = y))
g + geom_line() + coord_cartesian(ylim= c(-3,3)) 
